import { createFetchTransport } from '@system-one-ai/transport-fetch';
import assert from 'node:assert/strict';
import test from 'node:test';
import { APIError, ResponseValidationError, SystemOne, UnsupportedFeatureError, ValidationError } from '@system-one-ai/core';
import { openRouterAdapter } from '@system-one-ai/adapter-openrouter';
import { request, nativePayload, jsonResponse } from './fixtures.mjs';

// Independent fixtures from OpenRouter's Decisions wire contract, not generated by the adapter.
function payload() {
  return { ...nativePayload(), id: 'gen-dec-fixture', model: 'typesafe/jev-1.13-20260917', provider: 'TypeSafe', usage: { input_tokens: 215, output_tokens: 31, cost: 0.00000903 } };
}

test('OpenRouter sends Decisions with noul and preserves IDs, real model, cost, and native statistics', async () => {
  const providerOptions = { openrouter: { provider: { only: ['typesafe'], allow_fallbacks: false }, session_id: 'sdk-test', user: 'end-user', trace: { trace_id: 'trace-test' } } };
  let calls = 0;
  const client = new SystemOne({ adapter: openRouterAdapter, apiKey: 'openrouter-fixture', headers: { 'HTTP-Referer': 'https://example.test', 'X-OpenRouter-Title': 'Test App' }, transport: createFetchTransport(async (url, init) => {
    calls++;
    assert.equal(url, 'https://openrouter.ai/api/alpha/decisions');
    assert.equal(init.method, 'POST');
    assert.equal(init.redirect, 'manual');
    assert.equal(init.headers.get('authorization'), 'Bearer openrouter-fixture');
    assert.equal(init.headers.get('x-openrouter-title'), 'Test App');
    assert.equal(init.headers.get('ai-model-id'), null);
    assert.deepEqual(JSON.parse(init.body), {
      model: '~typesafe/jev-latest', state: request.state,
      questions: { ...request.questions, interrupt: { ...request.questions.interrupt, type: 'noul' } },
      provider: { only: ['typesafe'], allow_fallbacks: false }, session_id: 'sdk-test', user: 'end-user', trace: { trace_id: 'trace-test' },
    });
    return jsonResponse(payload(), { headers: { 'x-request-id': 'http-request-fixture' } });
  }) });
  const result = await client.evaluate({ ...request, providerOptions });
  assert.equal(calls, 1);
  assert.equal(result.model, 'typesafe/jev-1.13-20260917');
  assert.equal(result.response.adapter, 'openrouter');
  assert.equal(result.response.requestId, 'http-request-fixture');
  assert.deepEqual(result.providerMetadata.openrouter, { generationId: 'gen-dec-fixture', provider: 'TypeSafe', cost: 0.00000903 });
  assert.deepEqual(result.usage, { inputTokens: 215, outputTokens: 31, totalTokens: 246 });
  assert.deepEqual(result.answers.interrupt, { type: 'boolean', probability: 0.94 });
  assert.equal(result.answers.action.confidence, 0.73);
  assert.equal(result.answers.action.probabilities.drink, 0.86);
  assert.equal(result.answers.urgency.score, 1.6);
  assert.equal(result.answers.urgency.legend['2'], 'High');
});

for (const [baseURL, expected] of [
  ['https://openrouter.ai', 'https://openrouter.ai/api/alpha/decisions'],
  ['https://openrouter.ai/api/', 'https://openrouter.ai/api/alpha/decisions'],
  ['https://openrouter.ai/api/v1/', 'https://openrouter.ai/api/alpha/decisions'],
  ['https://openrouter.ai/api/alpha/', 'https://openrouter.ai/api/alpha/decisions'],
  ['https://openrouter.ai/api/alpha/decisions/', 'https://openrouter.ai/api/alpha/decisions'],
  ['https://proxy.example/tenant/api/alpha', 'https://proxy.example/tenant/api/alpha/decisions'],
  ['https://proxy.example/tenant/decisions', 'https://proxy.example/tenant/decisions'],
]) {
  test(`OpenRouter endpoint: ${baseURL}`, async () => {
    const client = new SystemOne({ baseURL, adapter: openRouterAdapter, apiKey: 'fixture', transport: createFetchTransport(async url => { assert.equal(url, expected); return jsonResponse(payload()); }) });
    await client.evaluate(request);
  });
}

test('explicit model IDs are sent unchanged; future providers need no new core code', async () => {
  const client = new SystemOne({ adapter: openRouterAdapter, model: 'vendor/reflex-2', apiKey: 'fixture', transport: createFetchTransport(async (_, init) => {
    assert.equal(JSON.parse(init.body).model, 'vendor/reflex-3');
    return jsonResponse({ ...payload(), model: 'vendor/reflex-3', provider: 'Future Provider' });
  }) });
  const result = await client.evaluate({ ...request, model: 'vendor/reflex-3' });
  assert.equal(result.model, 'vendor/reflex-3');
  assert.equal(result.rounding, undefined);
});

test('provider options cannot override the model, state, questions, or streaming behavior', async () => {
  const client = new SystemOne({ adapter: openRouterAdapter, apiKey: () => assert.fail('must fail before authentication'), transport: createFetchTransport(async () => assert.fail('must fail before network')) });
  for (const name of ['model', 'state', 'questions', 'stream']) {
    await assert.rejects(client.evaluate({ ...request, providerOptions: { openrouter: { [name]: 'override' } } }), UnsupportedFeatureError);
  }
  await assert.rejects(client.evaluate({ ...request, providerOptions: { gateway: {} } }), UnsupportedFeatureError);
  for (const options of [null, [], { session_id: 1 }, { session_id: 'x'.repeat(257) }, { user: null }, { trace: [] }, { provider: false }]) {
    await assert.rejects(client.evaluate({ ...request, providerOptions: { openrouter: options } }), ValidationError);
  }
});

test('nullable provider preference is passed through', async () => {
  const client = new SystemOne({ adapter: openRouterAdapter, apiKey: 'fixture', transport: createFetchTransport(async (_, init) => {
    assert.equal(JSON.parse(init.body).provider, null);
    return jsonResponse(payload());
  }) });
  await client.evaluate({ ...request, providerOptions: { openrouter: { provider: null } } });
});

test('optional metadata remains absent and a free request retains its reported zero cost', async () => {
  const raw = payload();
  delete raw.id;
  delete raw.provider;
  raw.usage.cost = 0;
  const client = new SystemOne({ adapter: openRouterAdapter, apiKey: 'fixture', transport: createFetchTransport(async () => jsonResponse(raw)) });
  assert.deepEqual((await client.evaluate(request)).providerMetadata.openrouter, { cost: 0 });
  delete raw.usage.cost;
  assert.deepEqual((await client.evaluate(request)).providerMetadata.openrouter, {});
});

for (const [label, mutate] of [
  ['unknown choice', raw => { raw.answers.action.choice = 'fly'; }],
  ['missing answer', raw => { delete raw.answers.interrupt; }],
  ['bad distribution', raw => { raw.answers.action.probabilities = { drink: 0.1, rest: 0.1 }; }],
  ['bad probability', raw => { raw.answers.interrupt.noul = 1.1; }],
  ['bad score', raw => { raw.answers.urgency.score = 0.1; }],
  ['bad usage', raw => { raw.usage.input_tokens = -1; }],
  ['missing resolved model', raw => { delete raw.model; }],
  ['bad ID', raw => { raw.id = {}; }],
  ['empty provider', raw => { raw.provider = ''; }],
  ['negative cost', raw => { raw.usage.cost = -1; }],
  ['null cost', raw => { raw.usage.cost = null; }],
  ['in-band error', raw => { raw.error = { message: 'upstream-failure-secret' }; }],
]) {
  test(`OpenRouter malformed responses fail without retry: ${label}`, async () => {
    const raw = payload(); mutate(raw);
    let calls = 0;
    const client = new SystemOne({ adapter: openRouterAdapter, apiKey: 'fixture', transport: createFetchTransport(async () => { calls++; return jsonResponse(raw); }) });
    await assert.rejects(client.evaluate(request), error => error instanceof ResponseValidationError && !error.message.includes('upstream-failure-secret'));
    assert.equal(calls, 1);
  });
}

test('OpenRouter HTTP failure preserves status and request ID without exposing error bodies', async () => {
  let calls = 0;
  const client = new SystemOne({ adapter: openRouterAdapter, apiKey: 'fixture', transport: createFetchTransport(async () => {
    calls++;
    return jsonResponse({ error: { message: 'credential-echo' } }, { status: 402, headers: { 'x-request-id': 'request-failed' } });
  }) });
  await assert.rejects(client.evaluate(request), error => error instanceof APIError && error.statusCode === 402 && error.requestId === 'request-failed' && !error.message.includes('credential-echo'));
  assert.equal(calls, 1);
});

test('TypeSafe rounding permits real rounded scores, while future providers must declare their rounding', async () => {
  const raw = payload();
  raw.answers.urgency = { type: 'score', score: 1.05, probabilities: { '0': 0, '1': 0.94, '2': 0.06 } };
  const client = new SystemOne({ adapter: openRouterAdapter, apiKey: 'fixture', transport: createFetchTransport(async () => jsonResponse(raw)) });
  assert.equal((await client.evaluate(request)).answers.urgency.score, 1.05);
  raw.model = 'future/reflex';
  await assert.rejects(client.evaluate(request), ResponseValidationError);
  raw.rounding = { probabilityDecimals: 2, scoreDecimals: 2 };
  assert.equal((await client.evaluate(request)).answers.urgency.score, 1.05);
});
